name: CI Github Pages

on:
  push:
    branches:
      - main  # 只监听main分支的push操作

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ️
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm  # 安装pnpm

      - name: Install dependencies and Build
        run: |
          pnpm install  # 使用pnpm安装依赖
          pnpm run build  # 使用pnpm构建项目

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages  # 部署到gh-pages分支
          folder: dist  # 打包后的目录